version: '3.4'

services:
  chat:
    image: "${DOCKER_REGISTRY-}chat"
    build:
      context: .
      dockerfile: Chat/Dockerfile 
    restart: always

  realtimechat.redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"